POST http://localhost:3333/preventive/service-orders/execute
Content-Type: application/json

{
    "id": 4195,
    "date": "Mon Feb 02 2026 00:00:00 GMT-0300 (Horário Padrão de Brasília)",
    "startTime": "Sun Dec 31 1899 11:51:00 GMT-0306 (Horário Padrão de Brasília)",
    "finishTime": "Sun Dec 31 1899 12:51:00 GMT-0306 (Horário Padrão de Brasília)",
    "workers": [
        {
            "id": 10
        },
        {
            "id": 3
        }
    ]
}
